management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  application:
    name: orders
  # Datasource properties with H2 as fallback
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    # Defer dialect setup to be automatic based on connection
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM:}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

---

# Profile for running tests. Uses a separate in-memory database.
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    # Show SQL for debugging tests
    show-sql: true
  flyway:
    enabled: true # Let flyway run for tests on H2
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: password
